export default [
    {
        id: '1',
        src: 'images/item.jpg',
        year: '2003',
        miles: '17,000KM',
        brand: 'Ferrari',
        dsc:'360 Challenge Stradale',
        label: 'New',
        price: 'HK$2,880,000',
        path: '/stock/itemDetails',
    },
    {
        id: '2',
        src: 'images/item7.jpg',
        year: '2022',
        miles: '82KM',
        brand: 'Ferrari',
        dsc:'Ferrari Roma',
        label: 'Tailor made',
        price: 'Price On Request',
        path: '/stock/itemDetails',
    },
    {
        id: '3',
        src: 'images/item3.jpg',
        year: '2016',
        miles: '17,539KM',
        brand: 'Ferrari',
        dsc:'Ferrari California T',
        label: 'New',
        price: 'HK$1,680,000',
        path: '/stock/itemDetails',
    },
    {
        id: '4',
        src: 'images/item4.jpg',
        year: '2021',
        miles: '760KM',
        brand: 'Ferrari',
        dsc:'Ferrari Roma',
        label: 'Sold',
        price: 'HK$3,088,000',
        path: '/stock/itemDetails',
    },
    {
        id: '5',
        src: 'images/item5.jpg',
        year: '2018',
        miles: '5,728KM',
        brand: 'Ferrari',
        dsc:'Ferrari Portofino',
        label: 'New',
        price: 'HK$2,780,000',
        path: '/stock/itemDetails',
    },
    {
        id: '6',
        src: 'images/item6.jpg',
        year: '2009',
        miles: '8,711KM',
        brand: 'Ferrari',
        dsc:'Scuderia Spider 16M',
        label: 'New',
        price: 'HK$3,880,000',
        path: '/stock/itemDetails',
    },
];